// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmZmws-6yhp097u6TM4Zcm5k-oL3pi8U0',
    appId: '1:419057044895:web:8a10a08c531e211d5081aa',
    messagingSenderId: '419057044895',
    projectId: 'recode-cfdf8',
    authDomain: 'recode-cfdf8.firebaseapp.com',
    storageBucket: 'recode-cfdf8.firebasestorage.app',
    measurementId: 'G-N5BWBBYL1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiDd3Ha7vwAk9ILxWNN8sgDib_XBM1JNw',
    appId: '1:419057044895:android:c6197a2d0ac2eba65081aa',
    messagingSenderId: '419057044895',
    projectId: 'recode-cfdf8',
    storageBucket: 'recode-cfdf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBivZCFGWV7Ptai5SEPz7xWOynu0DPFhM0',
    appId: '1:419057044895:ios:f9b2bccdf0f2baaa5081aa',
    messagingSenderId: '419057044895',
    projectId: 'recode-cfdf8',
    storageBucket: 'recode-cfdf8.firebasestorage.app',
    iosClientId: '419057044895-oitskjp89a2kuuv9m5juup6ohlphnqee.apps.googleusercontent.com',
    iosBundleId: 'com.example.recode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBivZCFGWV7Ptai5SEPz7xWOynu0DPFhM0',
    appId: '1:419057044895:ios:f9b2bccdf0f2baaa5081aa',
    messagingSenderId: '419057044895',
    projectId: 'recode-cfdf8',
    storageBucket: 'recode-cfdf8.firebasestorage.app',
    iosClientId: '419057044895-oitskjp89a2kuuv9m5juup6ohlphnqee.apps.googleusercontent.com',
    iosBundleId: 'com.example.recode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmZmws-6yhp097u6TM4Zcm5k-oL3pi8U0',
    appId: '1:419057044895:web:2bd6f5349d484d0f5081aa',
    messagingSenderId: '419057044895',
    projectId: 'recode-cfdf8',
    authDomain: 'recode-cfdf8.firebaseapp.com',
    storageBucket: 'recode-cfdf8.firebasestorage.app',
    measurementId: 'G-J58V8LKHF1',
  );
}
